language: haskell
sudo: false
services:
  - postgresql

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup --no-terminal

before_script:
  - psql -c 'create database pgstore_ci_tests;' -U postgres
  - export PGINFO="postgres://postgres@localhost/pgstore_ci_tests"

script:
  - stack build --no-terminal
  - stack test --no-terminal

cache:
  directories:
    - $HOME/.stack
